const SONGS = [
    { no: 1,  title: "You",                    album: 0, length: 209 },
    { no: 2,  title: "Creep",                  album: 0, length: 236 },
    { no: 3,  title: "How Do You?",            album: 0, length: 132 },
    { no: 4,  title: "Stop Whispering",        album: 0, length: 326 },
    { no: 5,  title: "Thinking About You",     album: 0, length: 161 },
    { no: 6,  title: "Anyone Can Play Guitar", album: 0, length: 218 },
    { no: 7,  title: "Ripcord",                album: 0, length: 190 },
    { no: 8,  title: "Vegetable",              album: 0, length: 193 },
    { no: 9,  title: "Prove Yourself",         album: 0, length: 145 },
    { no: 10, title: "I Can't",                album: 0, length: 253 },
    { no: 11, title: "Lurgee",                 album: 0, length: 188 },
    { no: 12, title: "Blow Out",               album: 0, length: 280 },

    { no: 1,  title: "Planet Telex",                 album: 1, length: 259 },
    { no: 2,  title: "The Bends",                    album: 1, length: 246 },
    { no: 3,  title: "High and Dry",                 album: 1, length: 257 },
    { no: 4,  title: "Fake Plastic Trees",           album: 1, length: 290 },
    { no: 5,  title: "Bones",                        album: 1, length: 189 },
    { no: 6,  title: "(Nice Dream)"	,                album: 1, length: 233 },
    { no: 7,  title: "Just",                         album: 1, length: 234 },
    { no: 8,  title: "My Iron Lung",                 album: 1, length: 276 },
    { no: 9,  title: "Bullet Proof... I Wish I Was", album: 1, length: 208 },
    { no: 10, title: "Black Star",                   album: 1, length: 247 },
    { no: 11, title: "Sulk",                         album: 1, length: 222 },
    { no: 12, title: "Street Spirit (Fade Out)",     album: 1, length: 252 },

    { no: 1,  title: "Airbag",                      album: 2, length: 284 },
    { no: 2,  title: "Paranoid Android",            album: 2, length: 383 },
    { no: 3,  title: "Subterranean Homesick Alien", album: 2, length: 267 },
    { no: 4,  title: "Exit Music (For A Film)",     album: 2, length: 264 },
    { no: 5,  title: "Let Down",                    album: 2, length: 299 },
    { no: 6,  title: "Karma Police",                album: 2, length: 261 },
    { no: 7,  title: "Fitter Happier",              album: 2, length: 117 },
    { no: 8,  title: "Electioneering",              album: 2, length: 230 },
    { no: 9,  title: "Climbing Up The Walls",       album: 2, length: 285 },
    { no: 10, title: "No Suprises",                 album: 2, length: 228 },
    { no: 11, title: "Lucky",                       album: 2, length: 259 },
    { no: 12, title: "The Tourist",                 album: 2, length: 230 },

    { no: 1,  title: "Everything in It's Right Place", album: 3, length: 251 },
    { no: 2,  title: "Kid A",                          album: 3, length: 284 },
    { no: 3,  title: "The National Anthem",            album: 3, length: 351 },
    { no: 4,  title: "How to Disappear Completely",    album: 3, length: 356 },
    { no: 5,  title: "Treefingers",                    album: 3, length: 222 },
    { no: 6,  title: "Optimistic",                     album: 3, length: 315 },
    { no: 7,  title: "In Limbo",                       album: 3, length: 211 },
    { no: 8,  title: "Idioteque",                      album: 3, length: 309 },
    { no: 9,  title: "Morning Bell",                   album: 3, length: 275 },
    { no: 10, title: "Motion Picture Soundtrack",      album: 3, length: 200 },
    { no: 11, title: "Untitled",                       album: 3, length:  52 },

    { no: 1,  title: "Packt Like Sardines in a Crushd Tin Box",  album: 4, length: 240 },
    { no: 2,  title: "Pyramid Song",                             album: 4, length: 289 },
    { no: 3,  title: "Pulk/Pull Revolving Doors",                album: 4, length: 247 },
    { no: 4,  title: "You and Whose Army",                       album: 4, length: 191 },
    { no: 5,  title: "I Might Be Wrong",                         album: 4, length: 294 },
    { no: 6,  title: "Knives Out",                               album: 4, length: 255 },
    { no: 7,  title: "Morning Bell/Amnesiac",                    album: 4, length: 194 },
    { no: 8,  title: "Dollars and Cents",                        album: 4, length: 292 },
    { no: 9,  title: "Hunting Bears",                            album: 4, length: 121 },
    { no: 10, title: "Like Spinning Plates",                     album: 4, length: 237 },
    { no: 11, title: "Life in a Glasshouse",                     album: 4, length: 271 },
    
    { no: 1,  title: "2 + 2 = 5",                  album: 5, length: 199 },
    { no: 2,  title: "Sit Down. Stand Up",         album: 5, length: 259 },
    { no: 3,  title: "Sail to the Moon",           album: 5, length: 258 },
    { no: 4,  title: "Backdrifts",                 album: 5, length: 322 },
    { no: 5,  title: "Go to Sleep",                album: 5, length: 321 },
    { no: 6,  title: "Where I End and You Begin",  album: 5, length: 269 },
    { no: 7,  title: "We Suck Young Blood",        album: 5, length: 296 },
    { no: 8,  title: "The Gloaming",               album: 5, length: 212 },
    { no: 9,  title: "There There",                album: 5, length: 325 },
    { no: 10, title: "I Will",                     album: 5, length: 119 },
    { no: 11, title: "A Punchup at a Wedding",     album: 5, length: 297 },
    { no: 12, title: "Myxomatosis",                album: 5, length: 232 },
    { no: 13, title: "Scatterbrain",               album: 5, length: 201 },
    { no: 14, title: "A Wolf at the Door",         album: 5, length: 201 },

    { no: 1,  title: "15 Step",                    album: 6, length: 238 },
    { no: 2,  title: "Bodysnatchers",              album: 6, length: 242 },
    { no: 3,  title: "Nude",                       album: 6, length: 255 },
    { no: 4,  title: "Weird Fishes / Arpeggi",     album: 6, length: 318 },
    { no: 5,  title: "All I Need",                 album: 6, length: 349 },
    { no: 6,  title: "Faust Arp",                  album: 6, length: 130 },
    { no: 7,  title: "Reckoner",                   album: 6, length: 290 },
    { no: 8,  title: "Jigsaw Falling Into Place",  album: 6, length: 328 },
    { no: 9,  title: "House of Cards",             album: 6, length: 249 },
    { no: 10, title: "Videotape",                  album: 6, length: 280 },

    { no: 1, title: 'Bloom',             album: 7, length: 315 },
    { no: 2, title: 'Morning Mr Magpie', album: 7, length: 281 },
    { no: 3, title: 'Little By Little',  album: 7, length: 267 },
    { no: 4, title: 'Feral',             album: 7, length: 193 },
    { no: 5, title: 'Lotus Flower',      album: 7, length: 301 },
    { no: 6, title: 'Give Up The Ghost', album: 7, length: 287 },
    { no: 7, title: 'Codex',             album: 7, length: 290 },
    { no: 8, title: 'Seperator',         album: 7, length: 320 },

    { no: 1,  title: "Burn The Witch",                album: 8, length: 220 },
    { no: 2,  title: "Daydreaming",                   album: 8, length: 384 },
    { no: 3,  title: "Decks Dark",                    album: 8, length: 281 },
    { no: 4,  title: "Desert Island Disk",            album: 8, length: 224 },
    { no: 5,  title: "Ful Stop",                      album: 8, length: 367 },
    { no: 6,  title: "Glass Eyes",                    album: 8, length: 172 },
    { no: 7,  title: "Identikit",                     album: 8, length: 266 },
    { no: 8,  title: "The Numbers",                   album: 8, length: 345 },
    { no: 9,  title: "Present Tense",                 album: 8, length: 306 },
    { no: 10, title: "Tinker Tailor Soldier Sailor",  album: 8, length: 303 },
    { no: 11, title: "True Love Waits",               album: 8, length: 283 },
];

const ALBUMS = [
    'Pablo Honey',
    'The Bends',
    'OK Computer',
    'Kid A',
    'Amnesiac',
    'Hail to the Thief',
    'In Rainbows',
    'The King of Limbs',
    'A Moon Shaped Pool',
];

const COVERS = [
    "https://upload.wikimedia.org/wikipedia/en/0/0f/Radiohead.pablohoney.albumart.jpg",
    "https://upload.wikimedia.org/wikipedia/en/5/55/Radioheadthebends.png",
    "https://upload.wikimedia.org/wikipedia/en/b/ba/Radioheadokcomputer.png",
    "https://upload.wikimedia.org/wikipedia/en/0/02/Radioheadkida.png",
    "https://upload.wikimedia.org/wikipedia/en/8/8c/Radiohead_-_Amnesiac_cover.png",
    "https://upload.wikimedia.org/wikipedia/en/6/61/Radioheadhailtothethief.png",
    "https://upload.wikimedia.org/wikipedia/en/1/14/Inrainbowscover.png",
    "https://upload.wikimedia.org/wikipedia/en/a/a2/Radioheadthekingoflimbs.png",
    "https://upload.wikimedia.org/wikipedia/en/6/6a/Amoonshapedpool.png",
];
